name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Update every 6 hours
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Generate GitHub-style Snake
        uses: Platane/snk@v3
        with:
          github_user_name: RitikaSingh1403
          outputs: |
            dist/github-contribution-snake.svg?palette=github-dark
            dist/github-contribution-snake.svg?palette=github-dark&color_snake=#ff6e96&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
          
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
